dist: xenial
install: sh installXenial.sh
script: sh buildXenial.sh
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_OAUTH_TOKEN
  file:
    - "r.zip"
  skip_cleanup: true
  on:
    tags: true